#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Jeremy Leggat <jleggat@asu.edu>
# --------------------------------------------------------------------------------
# 1. Promise vtrak chassis status

factory_settings["vtrak_chassis_default_levels"] = {
    "allowed_status" : ["OK"],
    "allowed_ready" : ["Active"],
    "transfer_rate" : "314572800", # 300MB
}

vtrak_chassis_role = { '-1': "na", '1': "primary", '2': "secondary" }

def inventory_vtrak_chassis(checkname, info):
  return [(line[0], {}) for line in info]

def check_vtrak_chassis(item, params, info):
  vtinfo = (line for line in info if line[0] == item)
  chk_info = vtinfo.next()

  # Performance counters
  datatransferred, readdatatransferred, writedatatransferred, numoferrors, numofnonrwerrors, \
    numofreaderrors, numofwriteerrors, numofiorequests, numofnonrwrequests, numofreadrequests, \
    numofwriterequests = map(int, chk_info[-11:])
  this_time = time.time()
  rates = []
  wrapped = False
  perfdata = [ ]
  for name, counter in [
    ( "DataTransferred", datatransferred ),
    ( "ReadDataTransferred", readdatatransferred ),
    ( "WriteDataTransferred", writedatatransferred ),
    ( "NumOfErrors", numoferrors ),
    ( "NumOfNonRWErrors", numofnonrwerrors ),
    ( "NumOfReadErrors", numofreaderrors ),
    ( "NumOfWriteErrors", numofwriteerrors ),
    ( "NumOfIORequests", numofiorequests ),
    ( "NumOfNonRWRequests", numofnonrwrequests ),
    ( "NumOfReadRequests", numofreadrequests ),
    ( "NumOfWriteRequests", numofwriterequests ) ]:
    try:
      timedif, rate = get_counter("vtrak.%s.%s" % (name, item), this_time, counter)
      rates.append(rate)
      perfdata.append( (name, rate) )
    except MKCounterWrapped:
      wrapped = True
      # continue, other counters might wrap as well

  # continue, other counters might wrap as well
  # after all counters are handled
  if wrapped: raise MKCounterWrapped("Counter wrap")

  perfdata.append( ("CacheUsagePercentage",saveint(chk_info[18]),"","",0,100) )
  perfdata.append( ("DirtyCachePercentage",saveint(chk_info[19]),"","",0,100) )


  ops = chk_info[2]
  readiness = chk_info[4]
  pdrives = chk_info[6]

  crit = False
  warn = False

  str_list = ["%s and %s" % (ops, readiness)]
  if chk_info[8] != '0':
     crit = True
     str_list.append("%s/%s offline" % (chk_info[8], pdrives))
  if chk_info[9] != '0':
    crit = True
    str_list.append("%s/%s Predictive Failure Analysis (PFA)" % (chk_info[9], pdrives))
  if chk_info[10] != '0':
    warn = True
    str_list.append("%s/%s rebuilding" % (chk_info[10], pdrives))
  if chk_info[11] != '0':
    crit = True
    str_list.append("%s/%s missing" % (chk_info[11], pdrives))
  if chk_info[12] != '0':
    warn = True
    str_list.append("%s/%s unconfigured" % (chk_info[12], pdrives))

  out_str = ' '.join(str_list)
  if crit:
    return (2, "CRITICAL - %s" % out_str, perfdata)
  elif warn:
    return (1, "WARN - %s" % out_str, perfdata)
  else:
    return (0, "OK - %s" % out_str, perfdata)

  return (3, "UNKNOWN - %s info not found" % item)

check_info["vtrak_chassis"] = {
    "inventory_function"       : inventory_vtrak_chassis,
    "check_function"           : check_vtrak_chassis,
    "has_perfdata"             : True,
    "service_description"      : "Array %s",
    "default_levels_variable"  : "vtrak_chassis_default_levels",
}

snmp_info["vtrak_chassis"] = \
	( ".1.3.6.1.4.1.7933.1.20.1", [
		"3.1.1",	# raidv4CtrlIndex
		"3.1.7",	# raidv4CtrlSerialNumber
		"3.1.15",	# raidv4CtrlOpStatus
		"3.1.16",	# raidv4CtrlRole			na(-1), primary(1), secondary(0)
		"3.1.17",	# raidv4CtrlReadinessStatus
		"3.1.18",	# raidv4CtrlNumOfArrayPresent
		"3.1.19",	# raidv4CtrlNumOfPhyDrvPresent
		"3.1.20",	# raidv4CtrlNumOfPhyDrvOnline
		"3.1.21",	# raidv4CtrlNumOfPhyDrvOffline
		"3.1.22",	# raidv4CtrlNumOfPhyDrvWithPFA
		"3.1.23",	# raidv4CtrlNumOfPhyDrvRebuilding
		"3.1.24",	# raidv4CtrlNumOfPhyDrvMissing
		"3.1.25",	# raidv4CtrlNumOfPhyDrvUnconfigured
		"3.1.26",	# raidv4CtrlNumOfLogDrvPresent
		"3.1.27",	# raidv4CtrlNumOfLogDrvOnline
		"3.1.28",	# raidv4CtrlNumOfLogDrvOffline
		"3.1.29",	# raidv4CtrlNumOfLogDrvCritical
		"3.1.64",	# raidv4CtrlNumOfLogDrvDegraded
		"3.1.38",	# raidv4CtrlDirtyCachePercentage	Values: na(-1)
		"3.1.39",	# raidv4CtrlCacheUsagePercentage	Values: na(-1)
		"4.1.1",    # raidv4CtrlStatsDataTransferred  Counter64
		"4.1.2",    # raidv4CtrlStatsReadDataTransferred  Counter64
		"4.1.3",    # raidv4CtrlStatsWriteDataTransferred  Counter64
		"4.1.4",    # raidv4CtrlStatsNumOfErrors  Integer32
		"4.1.5",    # raidv4CtrlStatsNumOfNonRWErrors  Integer32
		"4.1.6",    # raidv4CtrlStatsNumOfReadErrors  Integer32
		"4.1.7",    # raidv4CtrlStatsNumOfWriteErrors  Integer32
		"4.1.8",    # raidv4CtrlStatsNumOfIORequests  Counter64
		"4.1.9",    # raidv4CtrlStatsNumOfNonRWRequests  Counter64
		"4.1.10",   # raidv4CtrlStatsNumOfReadRequests  Counter64
		"4.1.11",   # raidv4CtrlStatsNumOfWriteRequests  Counter64
	] )

snmp_scan_functions['vtrak_chassis'] = \
    lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.7933.1.10")
