#!/bin/bash

# Check_mk plugin to check nginx
#
#	Version 1.1
#
# 2013-01-24 FLX f@qsol.ro
#	- Modified to use links
#
# 2012-09-27 FLX f@qsol.ro
#	- First  version
#

if which links && which nginx; then
	echo '<<<nginx>>>'
	#links -dump 127.0.0.1/nginx_status/
	links  -dump 127.0.0.1/nginx_status/ | sed ':a;N;$!ba;s/\n/ /g' | sed 's/server/\nserver/g' | sed 's/requests/requests\n/g' | sed 's/Reading/\nReading/g'
fi
