#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# --------------------------------------------------------------------------------
# 1. Fibre Channel Module Entry info
# Polls the .1.3.6.1.2.1.75.1.1.4 oid, FIBRE-CHANNEL-FE-MIB::fcFeModuleTable
# "A table that contains, one entry for each module in the Fabric Element, information of the modules."

def inventory_fc_entry(checkname, info):
  inventory = []
  for index, descr, objectid, operstatus, lastchange, fxportcapacity, name in info:
    if state == "2" or state == "3":
      inventory.append( (index, None) )
  return inventory

def check_fc_entry(item, _no_params, info):
  for index, descr, objectid, operstatus, lastchange, fxportcapacity, name in info:
    if index == item:
      if status == "3" or status == "9":
        return (0, "OK - " + speed + "mps")
      else:
        return (2, "CRITICAL - " + speed + "mps")
  return (3, "UNKNOWN - Port info not found")

check_info["fc_entry"] = \
      (check_fc_entry, "Port %s", 0, inventory_fc_entry)

snmp_info["fc_entry"] = \
	( ".1.3.6.1.2.1.75.1.1.4.1", [
		"1",	# fcFeModuleIndex
		"2",	# fcFeModuleDescr
		"3",	# fcFeModuleObjectID
		"4",	# fcFeModuleOperStatus	Values: online(1), offline(2), testing(3), faulty(4)
		"5",	# fcFeModuleLastChange
		"6",	# fcFeModuleFxPortCapacity
		"7",	# fcFeModuleName
	] )
snmp_scan_functions['fc_entry'] = \
  lambda oid: oid(".1.3.6.1.2.1.75.1.1.1") != None
