#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# --------------------------------------------------------------------------------
# 1. Fibre Channel Module unit info
# Polls the .1.3.6.1.2.1.75.1.1.4 oid, FIBRE-CHANNEL-FE-MIB::fcFeModuleTable
# "A table that contains, one unit for each module in the Fabric Element, information of the modules."
check_includes['fc'] = [ "fc.include" ]

def inventory_fc_unit(checkname, info):
  inventory = []
  for descr, status, portcapacity, name in info:
    inventory.append( (fc_hex2string(name), (descr,status,portcapacity,name)) )
  return inventory

def check_fc_unit(item, params, info):
  for descr, status, portcapacity, name in info:
    modname = fc_hex2string(name)
    if modname == item:
      opstatename = fc_statusname(status)
      msg_text = "%s %s - %s ports" % (descr, opstatename, portcapacity,)
      if status == "1":
        return (0, "OK - " + msg_text)
      else:
        return (2, "CRITICAL - " + msg_text)
  return (3, "UNKNOWN - System info not found")

check_info["fc_unit"] = \
      (check_fc_unit, "Unit %s", 0, inventory_fc_unit)

snmp_info["fc_unit"] = \
	( ".1.3.6.1.2.1.75.1.1.4.1", [
		"2",	# fcFeModuleDescr
		"4",	# fcFeModuleOperStatus	Values: online(1), offline(2), testing(3), faulty(4)
		"6",	# fcFeModuleFxPortCapacity
		"7",	# fcFeModuleName
	] )

snmp_scan_functions['fc_unit'] = \
  lambda oid: oid(".1.3.6.1.2.1.75.1.1.1.0") != None
