#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# --------------------------------------------------------------------------------
# 1. Fibre Alliance base info
# Polls the .1.3.6.1.3.94.1.6 oid, FCMGMT-MIB::connUnitEntry
# "A connectivity unit entry containing objects for a particular unit."

def fibrealliance_sys_itemname(id):
	return '.'.join(str(x) for x in (ord(byte) for byte in id))
def fibrealliance_sys_statename(st):
    names = { '1': "unknown", '2': "onlined", '3': "offline" }
    return names.get(st, st)
def fibrealliance_sys_statusname(st):
    names = { '1': "unknown", '2': "unused", '3': "ok", '4': "warning", '5': "failed" }
    return names.get(st, st)

def inventory_fibrealliance_sys(checkname, info):
  inventory = []
  for id, type, ports, state, status, product, sn, uptime, url, master, principal, sensors, name, event in info:
    inventory.append( (fibrealliance_sys_itemname(id), (type,ports,sensors)) )
  return inventory

def check_fibrealliance_sys(item, _no_params, info):
  for id, type, ports, state, status, product, sn, uptime, url, master, principal, sensors, name, event in info:
    if fibrealliance_sys_itemname(id) == item:
      if state == "2" and status == "3":
        return (0, "OK - online")
      else:
        return (2, "CRITICAL - ")
  return (3, "UNKNOWN - Switch info not found")

check_info["fibrealliance_sys"] = \
      (check_fibrealliance_sys, "Chasis %s", 0, inventory_fibrealliance_sys)

snmp_info["fibrealliance_sys"] = \
	( ".1.3.6.1.3.94.1.6.1", [
		"1",	# connUnitId
		"3",	# connUnitType	Values: unknown(1), other(2), hub(3), switch(4), gateway(5), converter(6), hba(7), proxy-agent(8), storage-device(9), host(10), storage-subsystem(11), module(12), swdriver(13), storage-access-device(14), wdm(15), ups(16), nas(17)
		"4",	# connUnitNumports
		"5",	# connUnitState	Values: unknown(1), online(2), offline(3)
		"6",	# connUnitStatus	Values: unknown(1), unused(2), ok(3), warning(4), failed(5)
		"7",	# connUnitProduct
		"8",	# connUnitSn
		"9",	# connUnitUpTime
		"10",	# connUnitUrl
		"12",	# connUnitProxyMaster	Values: unknown(1), no(2), yes(3)
		"13",	# connUnitPrincipal		Values: unknown(1), no(2), yes(3)
		"14",	# connUnitNumSensors
		"20",	# connUnitName
		"25",	# connUnitEventFilter	Values: unknown(1), emergency(2), alert(3), critical(4), error(5), warning(6), notify(7), info(8), debug(9), mark(10)
	] )

snmp_scan_functions['fibrealliance_sys'] = \
  lambda oid: oid(".1.3.6.1.3.94.1.1.0") != None
