#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Jeremy Leggat <jleggat@asu.edu>
# --------------------------------------------------------------------------------
# 1. Fibre Channel Module Entry info
# Polls the .1.3.6.1.4.1.122.8501 oid, FIBRE-CHANNEL-FE-MIB::fcFeModuleTable
# "A table that contains, one entry for each module in the Fabric Element, information of the modules."
# Reads:
#  .1.3.6.1.4.1.122.8501.3.101.4.1.0, location, String
#  .1.3.6.1.4.1.122.8501.3.101.1.1.0, model number, String
#  .1.3.6.1.4.1.122.8501.3.101.6.1.1.5.1, lamp hours, Counter32

def inventory_sony_vp(checkname, info):
  inventory = []
  for index, descr, objectid in info:
    if state == "2" or state == "3":
      inventory.append( (index, None) )
  return inventory

def check_sony_vp(item, _no_params, info):
  for index, descr, objectid in info:
    if index == item:
      if status == "3" or status == "9":
        return (0, "OK - " + speed + "mps")
      else:
        return (2, "CRITICAL - " + speed + "mps")
  return (3, "UNKNOWN - Port info not found")

check_info["sony_vp"] = \
      (check_sony_vp, "Port %s", 0, inventory_sony_vp)

snmp_info["sony_vp"] = ( ".1.3.6.1.4.1.122.8501", [ ".3.101.4.1.0", ".3.101.1.1.0", ".3.101.6.1.1.5.1" ] )
snmp_scan_functions['sony_vp'] = \
  lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.122.8501")