#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Jeremy Leggat <jleggat@asu.edu>
# --------------------------------------------------------------------------------
# 1. Promise VTrack Fan status

def vtrack_fans_typename(st):
    names = { '1': "fan", '2': "blower" }
    return names.get(st, st)

def inventory_vtrack_fans(checkname, info):
  inventory = []
  for index, type, status, speed in info:
    inventory.append( (index, None) )
  return inventory

def check_vtrack_fans(item, _no_params, info):
  for index, type, status, speed in info:
    if index == item:
      perfdata = [ ( "DeviceSpeed", speed) ]
      if status == "Functional":
        return (0, "OK - running at " + speed, perfdata)
      else:
        return (2, "CRITICAL - " + speed, perfdata)
  return (3, "UNKNOWN - fans not found")

check_info["vtrack_fans"] = \
      (check_vtrack_fans, "Fan %s", 1, inventory_vtrack_fans)

snmp_info["vtrack_fans"] = \
	( ".1.3.6.1.4.1.7933.1.20.1.11.1", [
		"1",	# raidv4CoolingDeviceIndex
		"2",	# raidv4CoolingDeviceType	Values: fan(0), blower(1)
		"3",	# raidv4CoolingDeviceStatus
		"4",	# raidv4CoolingDeviceSpeed
	] )
snmp_scan_functions['vtrack_fans'] = \
  lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.7933.1.10")
