#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Jeremy Leggat <jleggat@asu.edu>
# --------------------------------------------------------------------------------
# 1. Promise VTrack Power Supply status

def inventory_vtrack_power(checkname, info):
  inventory = []
  for index, status in info:
    if isinstance(status, str):
      inventory.append( (index, None) )
  return inventory

def check_vtrack_power(item, _no_params, info):
  for index, status in info:
    if index == item:
      if status == "Powered On and Functional":
        return (0, "OK - " + status)
      else:
        return (2, "CRITICAL - " + status)
  return (3, "UNKNOWN - power supply not found")

check_info["vtrack_power"] = \
      (check_vtrack_power, "PowerSupply %s", 0, inventory_vtrack_power)

snmp_info["vtrack_power"] = \
	( ".1.3.6.1.4.1.7933.1.20.1.12.1", [
		"1",	# raidv4PowerSupplyIndex
		"2",	# raidv4PowerSupplyStatus
	] )
snmp_scan_functions['vtrack_power'] = \
  lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.7933.1.10")
