#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Jeremy Leggat <jleggat@asu.edu>
# --------------------------------------------------------------------------------
# 1. Promise VTrack Temp Sensor status

def inventory_vtrack_temp(checkname, info):
  inventory = []
  for index, temperature, status in info:
    try:
      float(temperature)
    except ValueError:
      continue
    inventory.append( (index, None) )
  return inventory

def check_vtrack_temp(item, _no_params, info):
  for index, temperature, status in info:
    if index == item:
      perfdata = [ ( "Temperature", temperature) ]
      if status == "normal":
        return (0, "OK - " + status + ' - ' + temperature + 'C',perfdata)
      else:
        return (2, "CRITICAL - " + status + ' - ' + temperature + 'C',perfdata)
  return (3, "UNKNOWN - temp sensor not found")

check_info["vtrack_temp"] = \
      (check_vtrack_temp, "TempSensor %s", 1, inventory_vtrack_temp)

snmp_info["vtrack_temp"] = \
	( ".1.3.6.1.4.1.7933.1.20.1.13.1", [
		"1",	# raidv4TempSensorIndex
		"2",	# raidv4TempSensorTemperature
		"3", 	# raidv4TempSensorStatus
	] )
snmp_scan_functions['vtrack_temp'] = \
  lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.7933.1.10")
