#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Jeremy Leggat <jleggat@asu.edu>
# --------------------------------------------------------------------------------
# 1. Promise VTrack Voltage Sensor status

factory_settings["vtrack_voltage_default_levels"] = {
    "allowed_status" : ["nil"],
}

def inventory_vtrack_voltage(checkname, info):
  inventory = []
  for index, voltage in info:
    if 'V' in voltage:
      inventory.append( (index, None) )
  return inventory

def check_vtrack_voltage(item, _no_params, info):
  for index, voltage in info:
    if index == item:
      perfdata = [ ( "Voltage", voltage.replace("V", "")) ]
      if voltage:
        return (0, "OK - %s" % voltage, perfdata)
      else:
        return (2, "CRITICAL - %s" % voltage, perfdata)
  return (3, "UNKNOWN - voltage sensor not found")

check_info["vtrack_voltage"] = {
    "inventory_function"       : inventory_vtrack_voltage,
    "check_function"           : check_vtrack_voltage,
    "has_perfdata"             : True,
    "service_description"      : "VoltageSensor %s",
    "default_levels_variable"  : "vtrack_voltage_default_levels",
}

snmp_info["vtrack_voltage"] = \
	( ".1.3.6.1.4.1.7933.1.20.1.14.1", [
		"1",	# raidv4VoltageSensorIndex
		"2",	# raidv4VoltageSensorVoltage
	] )

snmp_scan_functions['vtrack_voltage'] = \
    lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.7933.1.10")
